### ISSUE TITLE
Markdown Badges

### ISSUE THREAD

**Issue by techyporcupine** [mrhappyma/mrhappyma#3]
Your markdown badges are floating slightly, you may want to add some margins/spacing.

**Comment by mrhappyma** [comment]
Yeah,I was thinking about it, more important things to do at the moment.

**Comment by mrhappyma** [comment]
I have no idea how to do this so it's not being fixed unless you can provide how :)

**Comment by mrhappyma** [comment]
wait what am i doing the badges dont exist anymore
